---
abstract: 'HTML Escape tainted data to prevent CSS Attacks'
author:
  - 'Fred Moyer <fred@redhotpenguin.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-TaintRequest
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Entities: 0
  Taint: 0
version: 0.01
